# Generated by Django 6.0.5 on 2026-05-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Ma thuat toan')),
                ('name', models.CharField(max_length=100, verbose_name='Ten thuat toan')),
                ('description', models.TextField(blank=True, verbose_name='Mo ta')),
                ('icon', models.CharField(default='⚙️', max_length=10, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang hoat dong')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
            ],
            options={
                'verbose_name': 'Thuat toan',
                'verbose_name_plural': 'Thuat toan',
                'db_table': 'algorithms',
                'ordering': ['name'],
            },
        ),
    ]
