# Generated by Django 6.0.5 on 2026-05-24 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Ten file goc')),
                ('stored_filename', models.CharField(max_length=255, unique=True, verbose_name='Ten file luu tru')),
                ('file_path', models.CharField(max_length=500, verbose_name='Duong dan file')),
                ('file_size', models.PositiveIntegerField(verbose_name='Kich thuoc (bytes)')),
                ('width', models.PositiveIntegerField(verbose_name='Chieu rong')),
                ('height', models.PositiveIntegerField(verbose_name='Chieu cao')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Loai MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi dung')),
            ],
            options={
                'verbose_name': 'Anh',
                'verbose_name_plural': 'Anh',
                'db_table': 'images',
                'ordering': ['-created_at'],
            },
        ),
    ]
