"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "your-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Dang ky module xac thuc nguoi dung.
    'apps.authentication.apps.AuthenticationConfig',
    # Dang ky module dashboard va admin panel Phase 1.
    'apps.dashboard.apps.DashboardConfig',
    'apps.admin_panel.apps.AdminPanelConfig',
    # Dang ky module upload va thu vien anh Phase 2.
    'apps.images.apps.ImagesConfig',
    # Dang ky module thuat toan OpenCV Phase 3.
    'apps.algorithms.apps.AlgorithmsConfig',
    # Dang ky module xu ly anh theo cau truc apps/.
    'apps.processing.apps.ProcessingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Ho tro ngon ngu tieng Viet cho message he thong.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Khai bao template root de dung cho toan he thong.
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                'core.context_processors.navigation_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        # Bat buoc su dung MySQL theo cau hinh .env.
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.getenv("DB_NAME", "lib-opencv"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            # Dam bao ket noi MySQL su dung utf8mb4 cho tieng Viet.
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "apps.authentication.validators.VietnameseUserAttributeSimilarityValidator",
    },
    {
        "NAME": "apps.authentication.validators.VietnameseMinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "apps.authentication.validators.VietnameseCommonPasswordValidator",
    },
    {
        "NAME": "apps.authentication.validators.VietnameseNumericPasswordValidator",
    },
    {
        "NAME": "apps.authentication.validators.VietnamesePasswordComplexityValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "vi"

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Asia/Ho_Chi_Minh"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Khai bao thu muc static local theo cau truc project.
STATICFILES_DIRS = [BASE_DIR / "static"]
# Khai bao url media de truyen file anh upload.
MEDIA_URL = "/media/"
# Khai bao duong dan luu media tren local.
MEDIA_ROOT = BASE_DIR / "media"

# Custom user model theo bang users trong pt-db.md.
AUTH_USER_MODEL = "authentication.User"
# URL dang nhap mac dinh khi truy cap trang can auth.
LOGIN_URL = "/auth/dang-nhap/"
# Chuyen huong sau khi dang nhap thanh cong.
LOGIN_REDIRECT_URL = "/dashboard/"
# Chuyen huong sau khi dang xuat.
LOGOUT_REDIRECT_URL = "/auth/dang-nhap/"

# Cau hinh CSRF cho moi truong dev local.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://127.0.0.1:8000,http://localhost:8000",
    ).split(",")
    if origin.strip()
]
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
# Cho phep truy cap HTTP local ma khong bi loi cookie.
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
