# Generated by Django 6.0.5 on 2026-05-24 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
        ('images', '0001_initial'),
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_filename', models.CharField(max_length=255, unique=True, verbose_name='Ten file luu tru')),
                ('file_path', models.CharField(max_length=500, verbose_name='Duong dan file')),
                ('file_size', models.PositiveIntegerField(verbose_name='Kich thuoc (bytes)')),
                ('width', models.PositiveIntegerField(verbose_name='Chieu rong')),
                ('height', models.PositiveIntegerField(verbose_name='Chieu cao')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100, verbose_name='Loai MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
            ],
            options={
                'verbose_name': 'Anh da xu ly',
                'verbose_name_plural': 'Anh da xu ly',
                'db_table': 'processed_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Cho xu ly'), ('processing', 'Dang xu ly'), ('completed', 'Hoan thanh'), ('failed', 'That bai')], default='pending', max_length=20, verbose_name='Trang thai')),
                ('error_message', models.TextField(blank=True, verbose_name='Loi')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thoi gian (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngay hoan thanh')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='algorithms.algorithm', verbose_name='Thuat toan')),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='images.image', verbose_name='Anh nguon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi dung')),
            ],
            options={
                'verbose_name': 'Processing Job',
                'verbose_name_plural': 'Processing Jobs',
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProcessingTask',
        ),
        migrations.AddField(
            model_name='processedimage',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_image', to='processing.processingjob', verbose_name='Processing job'),
        ),
    ]
