# Generated by Django 6.0.5 on 2026-05-24 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_processedimage_processingjob_delete_processingtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trang thai'),
        ),
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Bat dau'), ('finished', 'Hoan thanh'), ('error', 'Loi')], max_length=20, verbose_name='Hanh dong')),
                ('message', models.TextField(blank=True, verbose_name='Noi dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='processing.processingjob', verbose_name='Processing job')),
            ],
            options={
                'verbose_name': 'Processing History',
                'verbose_name_plural': 'Processing History',
                'db_table': 'processing_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_key', models.CharField(max_length=100, verbose_name='Ten tham so')),
                ('param_value', models.CharField(max_length=255, verbose_name='Gia tri')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='processing.processingjob', verbose_name='Processing job')),
            ],
            options={
                'verbose_name': 'Processing Parameter',
                'verbose_name_plural': 'Processing Parameters',
                'db_table': 'processing_parameters',
                'unique_together': {('job', 'param_key')},
            },
        ),
    ]
