# Generated by Django 6.0.5 on 2026-05-24 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
        ('processing', '0003_alter_processingjob_status_processinghistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('single', 'Xu ly don'), ('pipeline', 'Pipeline')], default='single', max_length=20, verbose_name='Loai job'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='algorithm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='algorithms.algorithm', verbose_name='Thuat toan'),
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(verbose_name='Thu tu buoc')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_steps', to='algorithms.algorithm', verbose_name='Thuat toan')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_steps', to='processing.processingjob', verbose_name='Processing job')),
            ],
            options={
                'verbose_name': 'Pipeline Step',
                'verbose_name_plural': 'Pipeline Steps',
                'db_table': 'pipeline_steps',
                'ordering': ['step_order'],
                'unique_together': {('job', 'step_order')},
            },
        ),
    ]
