# Generated by Django 6.0.5 on 2026-05-24 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0004_processingjob_job_type_alter_processingjob_algorithm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20, verbose_name='Muc do')),
                ('module', models.CharField(choices=[('processing', 'Xử lý ảnh'), ('pipeline', 'Pipeline'), ('images', 'Ảnh'), ('auth', 'Xác thực'), ('admin', 'Admin'), ('system', 'Hệ thống')], default='system', max_length=50, verbose_name='Module')),
                ('message', models.TextField(verbose_name='Noi dung')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thoi gian (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='processing.processingjob', verbose_name='Processing job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Nguoi dung')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='system_logs_created_9fcafe_idx'), models.Index(fields=['level', 'module'], name='system_logs_level_4c8c2a_idx')],
            },
        ),
    ]
